name: api
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  firebase_auth:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
