// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtEnPW7sw-KAKGQLcNf3WD8Z5ndcpXB7E',
    appId: '1:860110882392:web:1d9ee904b7c11610b2ec2d',
    messagingSenderId: '860110882392',
    projectId: 'api01-f9571',
    authDomain: 'api01-f9571.firebaseapp.com',
    storageBucket: 'api01-f9571.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUWh3gVavD2R1RCC_A2U-6lxqaVC-oC7k',
    appId: '1:860110882392:android:60387937ff1daf0db2ec2d',
    messagingSenderId: '860110882392',
    projectId: 'api01-f9571',
    storageBucket: 'api01-f9571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnqHpdir7o8PK-m2XqOC4MUstzZvv_jn4',
    appId: '1:860110882392:ios:c45d939822093bacb2ec2d',
    messagingSenderId: '860110882392',
    projectId: 'api01-f9571',
    storageBucket: 'api01-f9571.appspot.com',
    iosClientId: '860110882392-57deninf8eiso0beu5en9ai6t12fgn1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnqHpdir7o8PK-m2XqOC4MUstzZvv_jn4',
    appId: '1:860110882392:ios:c2ffec21ff5e8282b2ec2d',
    messagingSenderId: '860110882392',
    projectId: 'api01-f9571',
    storageBucket: 'api01-f9571.appspot.com',
    iosClientId: '860110882392-gfksi9hdpv02rmvllta0s5in5f2u5n7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.api.RunnerTests',
  );
}
